from .auth.register import register_user
from .auth.login import login
from .auth.logout import logout_user
from .auth.home import home
from .pets.list import pet_list
from .pets.form import pet_form
from .pets.details import pet_details
from .photos.list import gallery
from .photos.form import photo_form
from .photos.form import photo_edit_form
from .pets.form import pet_edit_form
from .photos.details import photo_details