from .auth.register import register_user
from .auth.login import login
from .auth.logout import logout_user
from .auth.home import home
from .pets.list import pet_list
from .pets.form import pet_form
from .pets.details import pet_details
from .gallery.list import gallery
from .photos.list import photo_list
from .photos.form import photo_form
from .photos.details import photo_details
from .kitten import kitten_image_view
from .kitten.kitten_image_view import success