# Generated by Django 3.1.1 on 2020-09-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_auto_20200917_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='favorite_toy',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gallery', to='catalogapp.photo'),
        ),
    ]
