# Generated by Django 3.1.1 on 2020-09-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_auto_20200919_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='pet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogapp.pet'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gallery', to='catalogapp.photo'),
        ),
    ]
