# Generated by Django 2.2.5 on 2020-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pet',
        ),
    ]
