# Generated by Django 2.2.5 on 2020-09-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_remove_photo_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitten',
        ),
    ]
