# Generated by Django 3.1.1 on 2020-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_auto_20200921_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
