# Generated by Django 3.1.1 on 2020-09-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0006_auto_20200921_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(),
        ),
    ]
